name: Build Packages

on:
  workflow_dispatch:
  push:
    paths:
      - 'luci-app-qosmate/**'
      - 'qosmate/**'

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64_generic

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Add Chinese translation
        run: |
         mkdir -p luci-app-qosmate/po/zh_Hans
         mv qosmate.po luci-app-qosmate/po/zh_Hans

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: qosmate
          PACKAGES: luci-app-qosmate
          NO_REFRESH_CHECK: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: qosmate_${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/qosmate/*.ipk

      - name: Get version and Compress
        run: |
          version=$(wget -qO- https://github.com/hudra0/qosmate/raw/main/etc/qosmate.sh | grep 'VERSION=' | sed -n 's/.*VERSION="\([^"]*\)".*/\1/p')
          echo "latest_version=v$version" >>$GITHUB_ENV
          tar -c -z -f qosmate_${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/qosmate .

      - name: Create and Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: qosmate-${{ env.latest_version }}
          tag: ${{ env.latest_version }}
          file_glob: true
          overwrite: true
          file: qosmate_${{ matrix.arch }}.tar.gz

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
